blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/RedHatProductSecurity/lola/discussions
    about: Ask questions, share ideas, and discuss lola with the community
  - name: Documentation
    url: https://github.com/RedHatProductSecurity/lola/blob/main/README.md
    about: Read the documentation to learn more about lola
  - name: Security Issue
    url: https://github.com/RedHatProductSecurity/lola/security/advisories/new
    about: Report security vulnerabilities privately
